services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DATABASE}

    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

    volumes:
      - postgres_lab_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

    networks:
      - lab-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DEFAULT_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


  inventoryservice:
    image: proyecto-muebles/inventoryservice:lab
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      DATABASE_URL: Host=postgres;Port=5432;Database=${INVENTORY_DATABASE};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true

    ports:
      - "${INVENTORY_PORT}:8080"

    networks:
      - lab-network

    depends_on:
      postgres:
        condition: service_healthy


  catalogservice:
    image: proyecto-muebles/catalogservice:lab
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

      # Temporalmente CatalogService consulta la misma base
      # que InventoryService porque lee inventory_products.
      DATABASE_URL: Host=postgres;Port=5432;Database=${INVENTORY_DATABASE};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true

    ports:
      - "${CATALOG_PORT}:8080"

    networks:
      - lab-network

    depends_on:
      postgres:
        condition: service_healthy
      inventoryservice:
        condition: service_started


networks:
  lab-network:
    driver: bridge


volumes:
  postgres_lab_data: