services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DATABASE}

    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

    volumes:
      - postgres_lab_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

    networks:
      - lab-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DEFAULT_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  lab-network:
    driver: bridge

volumes:
  postgres_lab_data:
