apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: muebles

resources:
  - namespace.yaml

  - postgres

  - authservice
  - catalogservice
  - cartservice
  - orderservice
  - paymentservice
  - inventoryservice

  - gateway
  - frontend

  - ingress.yaml